[package]
name = "http_server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "http_server"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
